"""Mapping from project country IDs to ISO 3166-1 alpha-2 codes."""

COUNTRY_ID_TO_ISO2 = {
    "argentina": "AR",
    "australia": "AU",
    "austria": "AT",
    "belgium": "BE",
    "brazil": "BR",
    "canada": "CA",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "costa_rica": "CR",
    "czechia": "CZ",
    "denmark": "DK",
    "egypt": "EG",
    "ethiopia": "ET",
    "finland": "FI",
    "france": "FR",
    "germany": "DE",
    "ghana": "GH",
    "greece": "GR",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "japan": "JP",
    "kenya": "KE",
    "mexico": "MX",
    "morocco": "MA",
    "netherlands": "NL",
    "new_zealand": "NZ",
    "nigeria": "NG",
    "norway": "NO",
    "pakistan": "PK",
    "poland": "PL",
    "portugal": "PT",
    "romania": "RO",
    "russia": "RU",
    "saudi_arabia": "SA",
    "singapore": "SG",
    "south_africa": "ZA",
    "south_korea": "KR",
    "spain": "ES",
    "sweden": "SE",
    "switzerland": "CH",
    "turkey": "TR",
    "uae": "AE",
    "uk": "GB",
    "ukraine": "UA",
    "usa": "US",
}

# Reverse lookup: ISO2 → country ID
ISO2_TO_COUNTRY_ID = {v: k for k, v in COUNTRY_ID_TO_ISO2.items()}
